print("============================================")
print("\tF1 TECHNICAL CONDE")
print("============================================")

print("\nPlease enter provide the following information")
first_name = input("First Name: ")
last_name = input("Last Name: ")
middle_name = input("Middle Name: ")
birthday = input("Birthday: ")
gender = input("Gender: ")
address = input("Address: ")
course = input("Course: ")
year_level = input("Year Level: ")
print("\nThank you for providing the information.")


print("\n\n============================================")
print("\tINFORMATION")
print("============================================")
print("Name: ", first_name, middle_name, last_name)
print("Birthday: ", birthday)
print("Gender", gender)
print("Address: ", address)
print("Course: ", course)
print("Year Level: ", year_level)
print("============================================")